# Generated by Django 4.2 on 2024-03-15 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
