# Generated by Django 4.2 on 2024-03-15 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_store_store_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
