# Generated by Django 4.2 on 2024-03-22 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_products_product_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
