# Generated by Django 4.2 on 2024-03-25 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_products_product_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_time', models.TimeField(default=django.utils.timezone.now)),
                ('transaction_qty', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('product_category', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_detail', models.TextField()),
            ],
        ),
    ]
