# Generated by Django 4.2 on 2024-03-25 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='transaction_time',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
