# Generated by Django 4.2 on 2024-03-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_sales_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='store_id',
            field=models.IntegerField(null=True),
        ),
    ]
